### PR TITLE
Jossversion

### PR DESCRIPTION
**Pull request by drannawatts**
Lots of small changes for the intended JOSS release (which will be v2.1.0).

I've bundled all changes since the last release in the CHANGELOG, made small changes to simplify the publications page, updated copyright year because I am too lazy to do this again on Jan 1, and tried to catch all of the v2.0.0 -> v2.1.0 changes needed. Please check carefully that I have caught all of them!

### CODE REVIEW

**Comment by thjsal** [comment]
I think you should update the version numbers in `neost/__init__.py` and in `docs/source/conf.py`.

**Comment by nr1118** [comment]
I also will modify the CHANGELOG on Thursday to account for the minor fix caught by Lucien when doing one of his practice runs!

**Comment by drannawatts** [comment]
Yikes, conf.py still has v1.0.0!  That's why my search didn't find it :-D  Will fix now, and the other file, thanks @thjsal !

**Comment by drannawatts** [comment]
And __init.py was still on v 0.10.0......  [screams in versioning]

**Review by nr1118 — APPROVED** [review]
Everything looks good! I have also did the minor fix that I had to make yesterday in regard to Lucien's issue and put it in the CHANGELOG. Oh and I changed one of the comments in PosteriorAnalysis.py to include future versions of NEoST since it references v2.0.0

**Pull request merged**
